name: 13 - Using Caching
on: 
    workflow_dispatch:
        inputs:
            use-cache:
              description: Whether to execute cache step
              type: boolean
              default: true
            node-version:
              description: node version
              type: choice
              options:
                - 18.x
                - 20.x
                - 21.x
              default: 20.x
            
    

jobs:
    build:
     runs-on: ubuntu-latest
     defaults:
        run:
            working-directory: 13-caching-actions/react-app
     steps:
        - name: CheckOut Code
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: ${{inputs.node-version}}
        - name: Download cached dependencies
          uses: actions/cache@v3
          if: ${{inputs.use-cache == true}}
          id: cache
          with:
            path: 13-caching-actions/react-app/node_modules
            key: deps-node-module-${{hashFiles('13-caching-actions/react-app/package-lock.json')}}
        - name: Cache status
          run: echo "Cache hit:" ${{ steps.cache.outputs.cache-hit }}
        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: npm ci
        - name: Testing
          run: npm run test
        - name: Building
          run: npm run build
        - name: deploying to nonprod
          run: echo "Depolying to nonprod"

